apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparta-node-deployment
spec:
  replicas: 2  # Starting with 2 replicas as per HPA requirements
  selector:
    matchLabels:
      app: sparta-node
  template:
    metadata:
      labels:
        app: sparta-node
    spec:
      containers:
        - name: sparta-app
          image: haashim1/haashim-node-website:multi
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: DB_HOST
              value: "mongodb://sparta-db-service:27017/posts"
            - name: EXECUTE_NPM_INSTALL
              value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparta-db-deployment
spec:
  replicas: 1  # Using 1 replica since we're using ReadWriteOnce PV
  selector:
    matchLabels:
      app: sparta-db
  template:
    metadata:
      labels:
        app: sparta-db
    spec:
      containers:
        - name: sparta-db
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: sparta-db-pvc
