apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparta-node-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sparta-node
  template:
    metadata:
      labels:
        app: sparta-node
    spec:
      containers:
        - name: sparta-app
          image: haashim1/haashim-node-website:latest # replace with the actual image name
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "mongodb://sparta-db-service:27017/posts" # Changed from DB_HOST=mongodb://...
            - name: EXECUTE_NPM_INSTALL
              value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparta-db-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sparta-db
  template:
    metadata:
      labels:
        app: sparta-db
    spec:
      containers:
        - name: sparta-db
          image: mongo:latest
          ports:
            - containerPort: 27017
