apiVersion: v1
kind: Service
metadata:
  name: sparta-node-service
spec:
  type: NodePort
  selector:
    app: sparta-node
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sparta-db-service
spec:
  selector:
    app: sparta-db
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
